const state={investors:JSON.parse(localStorage.getItem('psfInvestors')||'[]'),sourceUrl:localStorage.getItem('psfSourceUrl')||'',queue:JSON.parse(localStorage.getItem('psfQueue')||'[]')};
const $=s=>document.querySelector(s);const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const save=()=>{localStorage.setItem('psfInvestors',JSON.stringify(state.investors));localStorage.setItem('psfSourceUrl',state.sourceUrl);localStorage.setItem('psfQueue',JSON.stringify(state.queue))};
const status=(t,k='info')=>{$('#agentStatus').textContent=t;$('#agentStatus').dataset.kind=k};
const person=n=>{n=n.trim();return n.length>=4&&n.length<=90&&n.split(/\s+/).length>=2&&n.split(/\s+/).length<=7&&/[A-Za-z]/.test(n)&&!/^(home|about|contact|login|menu|privacy|terms|investors|portfolio|search|next|previous|read more)$/i.test(n)};
async function extract(url){const r=await fetch(url,{mode:'cors'});if(!r.ok)throw Error('HTTP '+r.status);const d=new DOMParser().parseFromString(await r.text(),'text/html'),a=[],seen=new Set();d.querySelectorAll('a').forEach(x=>{const n=x.textContent.replace(/\s+/g,' ').trim();if(!person(n)||seen.has(n.toLowerCase()))return;seen.add(n.toLowerCase());let s=url;try{s=new URL(x.getAttribute('href')||'',url).href}catch{}a.push({name:n,source:s})});return a.slice(0,200)}
const queries=n=>[`"${n}" investor`,`"${n}" LinkedIn investor`,`"${n}" fund venture capital`,`"${n}" portfolio investments`,`"${n}" email investor`,`"${n}" phone investor`,`"${n}" Mumbai investor`];
function queue(names){state.queue=names.map((x,i)=>{const n=typeof x==='string'?x:x.name,q=encodeURIComponent(`"${n}" investor`);return{id:Date.now()+i,name:n,source:typeof x==='string'?state.sourceUrl:(x.source||state.sourceUrl),queries:queries(n),google:`https://www.google.com/search?q=${q}`,bing:`https://www.bing.com/search?q=${q}`,researched:false}}).filter(x=>person(x.name));save();renderQueue()}
async function run(){const u=$('#sourceUrl').value.trim();try{new URL(u)}catch{return status('Enter a valid Website B URL.','error')}state.sourceUrl=u;save();status('Trying browser-side discovery…');try{const n=await extract(u);if(!n.length)throw Error('No names found');queue(n);$('#queuePanel').hidden=false;status(`Found ${n.length} investor candidates. Research queue ready.`,'success')}catch(e){$('#manualNamesPanel').hidden=false;status('Website B blocked browser access or did not expose names. No fake data was generated. Paste the investor names below.','warning')}}
function manual(){const n=$('#manualNames').value.split(/\r?\n|,/).map(x=>x.trim()).filter(person).map(name=>({name,source:state.sourceUrl}));if(!n.length)return status('No usable investor names found.','error');queue(n);$('#manualNamesPanel').hidden=true;$('#queuePanel').hidden=false;status(`Added ${n.length} investors to the research queue.`,'success')}
function renderQueue(){const e=$('#researchQueue');if(!e)return;e.innerHTML=state.queue.map((x,i)=>`<div class="queue-row"><div><strong>${i+1}. ${esc(x.name)}</strong><small>${esc(x.source)}</small></div><div class="queue-actions"><a target="_blank" href="${esc(x.google)}">Google</a><a target="_blank" href="${esc(x.bing)}">Bing</a><button data-copy="${i}">Copy queries</button><button data-mark="${i}">${x.researched?'Researched':'Mark researched'}</button></div></div>`).join('');$('#queueCount').textContent=`${state.queue.length} investors`}
function add(r){if(!r?.name)return;const k=r.name.toLowerCase().trim(),i=state.investors.findIndex(x=>String(x.name||'').toLowerCase().trim()===k);if(i>=0)state.investors[i]={...state.investors[i],...r};else state.investors.push(r);save();renderTable()}
function importJson(){try{const x=JSON.parse($('#importJson').value),a=Array.isArray(x)?x:(x.investors||[x]);a.forEach(add);$('#importJson').value='';status(`Imported ${a.length} records.`,'success')}catch{status('Invalid JSON.','error')}}
function renderTable(){const b=$('#investorTableBody');b.innerHTML=state.investors.map((x,i)=>`<tr><td>${esc(x.name)}</td><td>${esc(x.bio)}</td><td>${esc(x.followers)}</td><td>${esc(x.city)}</td><td>${esc(x.phone)}</td><td>${esc(x.email)}</td><td>${x.linkedin?`<a target="_blank" href="${esc(x.linkedin)}">LinkedIn</a>`:'—'}</td><td>${esc(x.status||'review')}</td><td>${esc(x.confidence??'—')}%</td><td>${(x.sources||[]).map(s=>`<a target="_blank" href="${esc(s)}">source</a>`).join(' · ')}</td><td><button data-delete="${i}">Delete</button></td></tr>`).join('');$('#investorCount').textContent=`${state.investors.length} records`}
function csv(){const c=['name','bio','followers','city','phone','email','linkedin','status','confidence','sources','notes'];const s=[c.join(','),...state.investors.map(x=>c.map(k=>`"${String(Array.isArray(x[k])?x[k].join(' | '):(x[k]??'')).replaceAll('"','""')}"`).join(','))].join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([s],{type:'text/csv'}));a.download='PSF-2027-Investor-Database.csv';a.click()}
function xlsx(){if(!window.XLSX)return alert('Excel library unavailable; use CSV.');const rows=state.investors.map(x=>({'Investor Name':x.name||'','LinkedIn Bio':x.bio||'','LinkedIn Followers':x.followers||'','City':x.city||'','Public Professional Phone':x.phone||'','Public Professional Email':x.email||'','LinkedIn':x.linkedin||'','Status':x.status||'','Confidence':x.confidence??'','Sources':(x.sources||[]).join(' | '),'Notes':x.notes||''})),ws=XLSX.utils.json_to_sheet(rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Investors');XLSX.writeFile(wb,'PSF-2027-Investor-Database.xlsx')}
document.addEventListener('click',async e=>{const c=e.target.closest('[data-copy]');if(c){await navigator.clipboard.writeText(state.queue[+c.dataset.copy].queries.join('\n'));c.textContent='Copied';setTimeout(()=>c.textContent='Copy queries',1000)}const m=e.target.closest('[data-mark]');if(m){state.queue[+m.dataset.mark].researched=!state.queue[+m.dataset.mark].researched;save();renderQueue()}const d=e.target.closest('[data-delete]');if(d){state.investors.splice(+d.dataset.delete,1);save();renderTable()}});
document.addEventListener('DOMContentLoaded',()=>{$('#sourceUrl').value=state.sourceUrl;$('#runResearchBtn').onclick=run;$('#addManualNamesBtn').onclick=manual;$('#importJsonBtn').onclick=importJson;$('#exportCsvBtn').onclick=csv;$('#exportXlsxBtn').onclick=xlsx;renderQueue();renderTable();status('Free GitHub Pages mode: no API key, no paid backend, no fake research.','success')});
